---
# Qdrant Docker handlers

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart qdrant
  community.docker.docker_compose_v2:
    project_src: "{{ qdrant_docker_data_dir }}"
    state: present
    recreate: always
